name: Check Docker Image
description: Check if Docker image tag exists

inputs:
  image_name:
    required: true
    description: Docker image name
  tag:
    required: true
    description: Docker image tag
  username:
    required: true
    description: Docker username
  password:
    required: true
    description: Docker password

outputs:
  exists:
    description: Whether the image exists
    value: ${{ steps.check.outputs.exists }}

runs:
  using: composite
  steps:
    - id: check
      shell: bash
      run: |
        # Login to Docker Hub
        echo "${{ inputs.password }}" | docker login -u "${{ inputs.username }}" --password-stdin

        # Extract repository name from full image name
        REPO_NAME=$(echo "${{ inputs.image_name }}" | cut -d'/' -f2)
        USERNAME=$(echo "${{ inputs.image_name }}" | cut -d'/' -f1)

        # Check if image exists using Docker Hub API
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
          "https://hub.docker.com/v2/repositories/$USERNAME/$REPO_NAME/tags/${{ inputs.tag }}")

        if [ "$HTTP_CODE" == "200" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
