name: Docker Login
description: Login to Docker registry

inputs:
  username:
    required: true
    description: Docker registry username
  password:
    required: true
    description: Docker registry password

runs:
  using: composite
  steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
