name: DockerBuild

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'beta/*' # beta/1.0.0

jobs:
  build:
    uses: ./.github/workflows/docker-build-job.yml
    with:
      dockerfile: Dockerfile
      image_name: masgeek/fuelrod-sms-portal
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
