name: Create PR to develop

on:
  push:
    branches-ignore:
      - main  # Exclude main branch
    # optional: you can use `branches: ['**']` if you want to explicitly allow all others

jobs:
  create-pr:
    runs-on: ubuntu-24.04
    if: github.ref != 'refs/heads/main'  # Extra safety check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create pull request to develop
        uses: devops-infra/action-pull-request@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Merge ${{ github.ref_name }} to develop"
          reviewer: ${{ github.actor }}
          assignee: ${{ github.actor }}
          target_branch: develop
          label: release
          old_string: "**Write you description here**"
          new_string: "${{ github.event.head_commit.message }}"
          body: "${{ github.event.head_commit.message }}"
          get_diff: false
